services:
  postgres:
    image: "postgres:12.2"
    volumes:
      -  db-data:/var/lib/postgresql/data
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  uvicorn:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: my_fastapi_app/Dockerfile
    networks:
      - default
    ports:
      - ${EXTERNAL_PORT}:8001
    depends_on:
      - postgres
    env_file: ./.env
    environment:
      HOSTNAME: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    entrypoint: ["python3", "-m", "uvicorn", "main_app:app", "--reload", "--port", "8001", "--host", "0.0.0.0"]
    # entrypoint: ["sleep", "100000"] 

volumes:
  db-data: {}

networks:
  default: {}
